### ISSUE TITLE
Is there any way to set the order of the headers ?

### ISSUE THREAD

**Issue by sharon182** [juanjoDiaz/json2csv#29]
Hi,
I'm using the NodeTransform module, and I'm wondering how to sort the csv headers by a custom order and just as the properties were set on the object record. 
Thanks 🙏

**Comment by juanjoDiaz** [comment]
Hi @sharon182 ,

The best way to do that would be to use the `fields` property and manually set the headers in the order that you want.

This is because JSON objects are unordered. Some implementations might preserve the order in which properties were declared. But following the standard, that is not strictly necessary.

**Comment by sharon182** [comment]
@juanjoDiaz 
I have tried that, but then i get a csv file with an empty records (the headers are fine).
Here's the options that I pass to the parser : 
```js
    const opts = {
      fields: Array.from(headersMap.values()),
      transforms: [
        (records: any) => {
          const flattenRecords = this.utility.convertRecords(records);
          return flattenRecords; //array of new transformed records
        },
        (record: any) => {
          Object.keys(record).forEach((key) => {
            if (record[key] === 'null') {
              record[key] = '';
            }
          })
          return record;
        }
      ],
    };

```

Missing anything ?

**Comment by juanjoDiaz** [comment]
`Array.from(headersMap.values()),` seems incorrect. You probably want `Array.from(headersMap.keys())`, don't you?
IT's a bit hard to know without knowing how your data looks like or what `headerMap` is.

Btw, `json2csv/transformers` already includes a flattening transform. I recommend that you use that as it's proven and performant.

**Comment by juanjoDiaz** [comment]
Closing as a solution was provided.
Feel free to reopen if you thing that there is still something to discuss.

**Comment by sanderfish** [comment]
I ran into the same, or a similar issue. My dataset is dynamic, so I don't know all the headers upfront.

I can use the stream to generate the headers (fields) and pass those to the Transform function via the `fields` property.

The reason the CSV file comes out empty in this case is that the stream can only be consumed once. After the first pass, the stream is exhausted and there's no data left for the second pass, which is why I'm only seeing the headers in my CSV file.

I can use `clonable-readable` library to duplicate the stream, but that affects performance.

Do you have any suggestions @juanjoDiaz?

This is my code:

```
  let fields = new Set();

  dbStream.on('data', (chunk) => {
    const data = transformFunction(chunk);
    const flattened = flatten({ objects: true })(data);

    Object.keys(flattened).forEach((key) => fields.add(key));
  });

  // Wait for the first pass to finish
  await new Promise((resolve) => dbStream.on('end', resolve));

  const parser = new Transform(
    {
      fields: Array.from(fields.keys()),
      transforms: [
        transformFunction,
        flatten({
          objects: true,
        }),
      ],
    },
    {
      objectMode: true,
    },
  );
```

**Comment by juanjoDiaz** [comment]
You certainly can't consume a stream twice. That's the whole point 🙂 

In your code example. You simply gather the headers but don't apply any particular order to them.
For that you could simply not provide the `fields` option at all and let the library figures them out.
Or do you want any specific order in your headers?

I also notice that you are finding all the existing headers in your dataset.
This library, unless you provide the `fields` option, only considers the properties in the first object.
Is this what you want to achieve?
The only way to consider all the headers into all the objects is to consume the entire stream and then consume it again to generate the CSV. And, as you already figured, it will have a hit on performance.

**Comment by sanderfish** [comment]
Thanks for your reply! The dataset is dynamic (they are responses to a form builder), so we will need to consider all the headers from all the objects. Sounds like we will indeed have to consume the stream twice.
