### ISSUE TITLE
Can't use Parsers with Vue3/Vite

### ISSUE THREAD

**Issue by UglyHobbitFeet** [juanjoDiaz/json2csv#59]
I can copy/paste the code shown in the examples for AsyncParser, but they will not work when run using NodeJs/Vite/Vue3.  I see the following in the logs:

```
2.224 vite v4.4.10 building for production...
2.618 transforming...
10.70 [plugin:vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "/app/node_modules/@json2csv/node/dist/mjs/AsyncParser.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
10.70 [plugin:vite:resolve] Module "os" has been externalized for browser compatibility, imported by "/app/node_modules/@json2csv/node/dist/mjs/Transform.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
10.70 [plugin:vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "/app/node_modules/@json2csv/node/dist/mjs/Transform.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
12.59 ✓ 1268 modules transformed.
12.59 ✓ built in 10.37s
12.60 "Transform" is not exported by "__vite-browser-external", imported by "node_modules/@json2csv/node/dist/mjs/Transform.js".
12.60 file: /app/node_modules/@json2csv/node/dist/mjs/Transform.js:2:9
12.60 1: import os from 'os';
12.60 2: import { Transform, } from 'stream';
12.60             ^
12.60 3: import { StreamParser, } from '@json2csv/plainjs';
12.60 4: export default class JSON2CSVNodeTransform extends Transform {
12.60 error during build:
12.60 RollupError: "Transform" is not exported by "__vite-browser-external", imported by "node_modules/@json2csv/node/dist/mjs/Transform.js".
12
```

Clicking on the link in the error (https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility) says to contact the developer.

**Comment by juanjoDiaz** [comment]
If you are using Vue, you are on the front.
You should use the plainjs flavour of json2csv instead of the node one, so you don't depend on node internals and don't need to polyfill.

You error says that whatever polyfill Vite is using is missing the Transform class from node.

**Comment by UglyHobbitFeet** [comment]
Thanks, that let me get past the issue and I can use the Parser object as expected.  Maybe it's just me but how do you pass myData to StreamParser?  The examples don't show how and there is no streamParser.parse(myData) method that I can see

**Comment by juanjoDiaz** [comment]
You can call the `write` method.
`streamParser.write(myData)` where `myData` can be a a string, and array or a binary array.

Also, if you are getting your data from an endpoint, I recommend that you look into the whatwg interface as it's a better abstraction.

**Comment by UglyHobbitFeet** [comment]
Thanks, but it's still not clear to me.  For example, how do I pass it a file name to output the csv to?  It would be great if the examples in the README file were updated to show the write method and its proper usage.  Thanks!

**Comment by UglyHobbitFeet** [comment]
btw I should not that the JSON mentioned above works fine with regular parser

```
      let outputAsObject = [{ some valid json data in object form}];
      const parser = new Parser(opts);
      const csv = parser.parse(outputAsObject);
```

**Comment by juanjoDiaz** [comment]
Hi, 

`StreamParser` is designed to handle string or bytearrays representing a string.

If you object is a JSON object, means that you already have it in memory and that it's not huuuuge.
So, I'd recommend that you use the sync parser as it is the fastest
```js
      let outputAsObject = [{ some valid json data in object form}];
      const parser = new Parser(opts);
      const csv = parser.parse(outputAsObject);
```

If you want to use the async approach to send the json in chunks and don't block the event loop, you can use `StreamParser` in object mode:
```js
const parser = new StreamParser(opts, { objectMode: true });
// ...
outputAsObject.forEach(obj => parser.write(obj));
```

The StreamParser in binary mode (default) is useful when you are getting your object as a byte stream. For example, from an HTTP request.
Although, the WHATWG interface is better to handle requests.

The problem with your code is that you have set incorrectly the `onData` callback.
You have:ç
```js
parser.onData = (chunk) => () => csv += chunk.toString();
```
and it should be
```js
parser.onData = (chunk) => csv += chunk.toString();
```

Then, the problem with the second write is that `StreamParser` auto-end when the full array is parsed. 
This is because a second array might have different headers and be very different.
If you want to process more than one array, you need to specify what the separator should be. If you have them just one after the other without any space, new line or any other separator, then you can use the empty string as separator.
This is currently not working due to a bug that you just uncovered. I'll fix it asap.
Then this should allow you to parse many consecutive json arrays separated by nothing:
```js
const parser = new StreamParser(opts, { separator: '' });
```

The docs are in the repo, so feel free to contribute any improvements that you think that might help other users 🙂
